import * as codemirrorThemes from "@uiw/codemirror-themes-all";
import { loadLanguage, langNames } from "@uiw/codemirror-extensions-langs";

export const themesBG = {
  ABCDEF: "#0f0f0f",
  "Android Studio": "#282b2e",
  "Atom One": "#272c35",
  "BB Edit": "#ffffff",
  Bespin: "#28211c",
  Darcula: "#2b2b2b",
  Dracula: "#282a36",
  "Duotone Dark": "#2a2734",
  "Duotone Light": "#faf8f5",
  Eclipse: "#ffffff",
  "Github Dark": "#0d1117",
  "Github Light": "#ffffff",
  Okaidia: "#272822",
  Sublime: "#303841",
  "XCode Dark": "#292a30",
  "XCode Light": "#ffffff",
};

export const themes = {
  ABCDEF: codemirrorThemes.abcdef,
  "Android Studio": codemirrorThemes.androidstudio,
  "Atom One": codemirrorThemes.atomone,
  "BB Edit": codemirrorThemes.bbedit,
  Bespin: codemirrorThemes.bespin,
  Darcula: codemirrorThemes.darcula,
  Dracula: codemirrorThemes.dracula,
  "Duotone Dark": codemirrorThemes.duotoneDark,
  "Duotone Light": codemirrorThemes.duotoneLight,
  Eclipse: codemirrorThemes.eclipse,
  "Github Dark": codemirrorThemes.githubDark,
  "Github Light": codemirrorThemes.githubLight,
  Okaidia: codemirrorThemes.okaidia,
  Sublime: codemirrorThemes.sublime,
  "XCode Dark": codemirrorThemes.xcodeDark,
  "XCode Light": codemirrorThemes.xcodeLight,
};

export const extensions = {
  jsx: ".jsx",
  tsx: ".tsx",
  rust: ".rs",
  mysql: ".sql",
  javascript: ".js",
  css: ".css",
  html: ".html",
  json: ".json",
  markdown: ".md",
  python: ".py",
  sass: ".sass",
  scss: ".scss",
  less: ".less",
  sql: ".sql",
  typescript: ".ts",
  xml: ".xml",
  yaml: ".yaml",
  c: ".c",
  cpp: ".cpp",
  java: ".java",
  php: ".php",
  csharp: ".cs",
  apl: ".apl",
  asciiarmor: ".asc",
  asterisk: ".conf",
  brainfuck: ".bf",
  scala: ".scala",
  kotlin: ".kt",
  shader: ".glsl",
  nesc: ".nc",
  objetiveC: ".m",
  objetiveCpp: ".mm",
  squirrel: ".nut",
  dart: ".dart",
  ceylon: ".ceylon",
  cmake: ".cmake",
  cobol: ".cobol",
  coffeescript: ".coffee",
  livescript: ".ls",
  solidity: ".sol",
  r: ".r",
  clojure: ".clj",
  go: ".go",
  lua: ".lua",
  perl: ".pl",
  ruby: ".rb",
  pascal: ".pas",
};
